# Generated by Django 5.2.2 on 2025-09-01 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('planting_season', models.CharField(max_length=50)),
                ('growth_period_days', models.IntegerField()),
                ('optimal_temp_min', models.FloatField()),
                ('optimal_temp_max', models.FloatField()),
                ('optimal_rainfall_min', models.FloatField()),
                ('optimal_rainfall_max', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, help_text='Country where the location is.', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(choices=[('GPS', 'GPS'), ('IP', 'IP-based'), ('CITY', 'Manual City Input')], default='CITY', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crops.location')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='crops.location')),
            ],
        ),
    ]
